name: build

on: [push]

jobs:
  build:

    runs-on: windows-latest  

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '5.0.x'
      - name: Install dependencies      
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger trx
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: xUnit Tests            # Name of the check run which will be created
          path: BESM3CAData.Test/TestResults/*.trx    # Path to test results
          reporter: dotnet-trx        # Format of test results
