name: build

on: [push]

jobs:
  build:

    runs-on: windows-latest  

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '6.0.x'
      - name: Install dependencies      
        run: dotnet restore
      - name: Build Library
        run: |
          cd BESM3CAData
          dotnet build --configuration Release --no-restore
          cd ..
      - name: Build Test Project 
        run: |
          cd BESM3CAData.Test
          dotnet build --configuration Release --no-restore
          cd ..
      - name: Run Tests
        run: dotnet test --configuration Release --no-restore --no-build --verbosity normal --logger trx        
      - name: Produce Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: xUnit Tests            # Name of the check run which will be created
          path: BESM3CAData.Test/TestResults/*.trx    # Path to test results
          reporter: dotnet-trx        # Format of test results          
      - name: Build Application
        run: dotnet build --configuration Release --no-restore         # Todo: deploy app
